# Prometheus configuration for GoLLuM
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gollum'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          instance: 'gollum-local'

